### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by qweaszxcdf** [Rhilip/cn-mooc-dl#2]
course_url = "http://www.xuetangx.com/courses/course-v1:TsinghuaX+20440333X+sp/about"

Traceback (most recent call last):
  File "xuetangx-dl.py", line 182, in <module>
    main(course_url)
  File "xuetangx-dl.py", line 102, in main
    tab_list[tab.get('id')] = re.search("(.+)", tab.get('title')).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Rhilip** [comment]
个人感觉你是参加课程后，未点开课程页面学习过。
xuetangx在第一次打开时候，并不返回真正的页面。所以脚本抓不到。。
（这个问题我遇到过。

如果是这种情况，请重新运行脚本后（这种情况二次运行就可解决），请告知运行情况；
否则，请告知你的其他信息，因为xuetangx的课程只有参加后才能抓取，没法复现。

**Comment by qweaszxcdf** [comment]
I re-run the script,and here is the output
[1.txt](https://github.com/Rhilip/cn-mooc-dl/files/1071093/1.txt)
