### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by jiangtiandao** [Rhilip/cn-mooc-dl#7]
Course url
https://www.icourse163.org/learn/NUDT-1001615004?tid=1001692001

Traceback (most recent call last):
  File "icourse163-dl.py", line 215, in <module>
    main()
  File "icourse163-dl.py", line 133, in main
    lesson_name = model.clean_filename(model.raw_unicode_escape(lesson_re.group("lesson_name")))
  File "D:\Users\John\Documents\GitHub\cn-mooc-dl\model\download.py", line 59, in raw_unicode_escape
    return string.encode('utf-8').decode('unicode_escape').encode('gbk', 'ignore').decode('gbk', 'ignore')
UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 36: \ at end of string

**Comment by jiangtiandao** [comment]
是末尾的  \ 在  Unicode escape 解码时 出错了

**Comment by jiangtiandao** [comment]
```Python
def raw_unicode_escape(string: str) -> str:
    return string.rstrip('\\').encode('utf-8').decode('unicode_escape').encode('gbk', 'ignore').decode('gbk', 'ignore')
```
